export const KERANJANG_ADD_ITEM = 'KERANJANG_ADD_ITEM'
export const KERANJANG_REMOVE_ITEM = 'KERANJANG_REMOVE_ITEM'

export const KERANJANG_SAVE_SHIPPING_ADDRESS = 'KERANJANG_SAVE_SHIPPING_ADDRESS'

export const KERANJANG_SAVE_PAYMENT_METHOD = 'KERANJANG_SAVE_PAYMENT_METHOD'